# ---
# - name: Installation of LEMP on amazon linux
#   hosts: localhost
#   become: yes 
#   tasks:
#    - name: install nginx webserver
#      ansible.builtin.dnf:
#        name: nginx
#        state: present

#    - name: install mariadb
#      ansible.builtin.dnf:
#        name: mariadb105-server
#        state: present

#    - name: install php
#      ansible.builtin.dnf:
#        name:
#         - php
#         - php-fpm
#        state: present

#    - name: start and enable nginx
#      ansible.builtin.systemd_service:
#        name: nginx
#        state: started
#        enabled: true

#    - name: start mariadb
#      ansible.builtin.systemd_service:
#        name: mariadb
#        state: started
#        enabled: true

#    - name: start php-fpm
#      ansible.builtin.systemd_service:
#        name: php-fpm
#        state: started
#        enabled: true
 
#    - name: deploymet of php application
#      ansible.builtin.copy:
#        dest: /usr/share/nginx/html/index.php
#        content: |
#          <?php
#          phpinfo();

---
- name: Installation lemp on nginx
  hosts: localhost
  become: yes
  tasks:
    - name: Install Lemp on nginx
      ansible.builtin.dnf:
       name: "{{web_pkg}}"
       state: present

    - name: Install db-server
      ansible.builtin.dnf:
       name: "{{db_pkg}}"
       state: present

    - name: Install php
      ansible.builtin.dnf:
       name: "{{php_pkg}}"
       state: present

    - name: start webserver
      ansible.builtin.systemd.service:
       name: "{{web_pkg}}"
       state: started
       enabled: true

    - name: start db-server
      ansible.builtin.systemd.server:
       name: "{{db_service}}"
       state: started
       enabled: true
    
    - name: start php
      ansible.builtin.systemd.server:
       name: "{{php_service}}"
       state: started
       enabled: true
    
    - name: deploy-php
      ansible.builtin.copy:
       dest: "{{php_file_path}}"
       content: |
          <?php 
            phpinfo()
            ?>