---
 - name: Installation of lamp using variable
   hosts: localhost
   become: yes
   vars:
     web_pkg: httpd
     db_pkg: mariadb105-server
     php_pkg:
        - php
        - php-fpm
     web_service: httpd
     db_service: mariadb
     php_service: php-fpm
     php_file_path: /var/www/html/index.php

   tasks:
    - name: Install Lamp on nginx
      ansible.builtin.dnf:
       name: "{{web_pkg}}"
       state: present

    - name: Install db-server
      ansible.builtin.dnf:
       name: "{{db_pkg}}"
       state: present

    - name: Install php
      ansible.builtin.dnf:
       name: "{{php_pkg}}"
       state: present

    - name: start webserver
      ansible.builtin.systemd.service:
       name: "{{web_pkg}}"
       state: started
       enabled: true

    - name: start db-server
      ansible.builtin.systemd.service:
       name: "{{db_service}}"
       state: started
       enabled: true
    
    - name: start php
      ansible.builtin.systemd.service:
       name: "{{php_service}}"
       state: started
       enabled: true
    
    - name: deploy-php
      ansible.builtin.copy:
       dest: "{{php_file_path}}"
       content: |
          <?php 
            phpinfo()
            ?>