# ---
# - name: Installation of LEMP on amazon linux
#   hosts: localhost
#   become: yes 
#   tasks:
#    - name: install nginx webserver
#      ansible.builtin.dnf:
#        name: nginx
#        state: present

#    - name: install mariadb
#      ansible.builtin.dnf:
#        name: mariadb105-server
#        state: present

#    - name: install php
#      ansible.builtin.dnf:
#        name:
#         - php
#         - php-fpm
#        state: present

#    - name: start and enable nginx
#      ansible.builtin.systemd_service:
#        name: nginx
#        state: started
#        enabled: true

#    - name: start mariadb
#      ansible.builtin.systemd_service:
#        name: mariadb
#        state: started
#        enabled: true

#    - name: start php-fpm
#      ansible.builtin.systemd_service:
#        name: php-fpm
#        state: started
#        enabled: true
 
#    - name: deploymet of php application
#      ansible.builtin.copy:
#        dest: /usr/share/nginx/html/index.php
#        content: |
#          <?php
#          phpinfo();

